customers/urls.py
from django.urls import path

from . import views

app_name = 'customers'
urlpatterns = [
    path('', views.CreateCustomer.as_view(), name='create'),
    path('update/<int:pk>/', views.UpdateCustomer.as_view(), name='update'),
    path('car/', views.CreateCar.as_view(), name='create_car'),
]

maktab64/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('rosetta/', include('rosetta.urls')),
    path('', include('customers.urls')),
    prefix_default_language=True
)

customers/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _


# Create your models here.

class Customer(models.Model):
    name = models.CharField(max_length=150, help_text=_('name of customer'))
    email = models.EmailField(unique=True)
    birthday = models.DateField(null=True, blank=True, verbose_name='b date')
    phone = models.CharField(max_length=13)
    address = models.TextField(null=True, blank=True)
    image = models.ImageField(null=True, blank=True, )
    status = models.BooleanField(null=True, blank=True)

    def __str__(self):
        return f'{self.name} - {self.email} - {self.phone}'

    class Meta:
        verbose_name = _('مشتری')
        verbose_name_plural = _('Customers')

    def count_car(self):
        return self.car_set.count()

    count_car.short_description = "his cars"


class Car(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    car_name = models.CharField(max_length=120)
    price = models.PositiveIntegerField()


class Club(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.PROTECT)
    name = models.CharField(max_length=100)

customers/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _
from customers.models import Customer, Car
from customers.validators import check_phone


#
# class CustomerForm(forms.Form):
#     name = forms.CharField(max_length=150, label='Full name')
#     email = forms.EmailField(help_text='customer email')
#     birthday = forms.DateField(required=False, error_messages={'invalid': 'Error, example 10/10/2020 '},
#                                widget=forms.SelectDateWidget)
#     phone = forms.CharField(max_length=13, required=False)
#     address = forms.CharField(widget=forms.Textarea)
#     status = forms.IntegerField(required=False)
#     image = forms.ImageField()
#     file = forms.FileField()


class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        # fields = '__all__'
        exclude = ['status', ]
        labels = {
            'name': _('Full Name'),
            'birthday': _('Birthday')
        }

        widgets = {
            'email': forms.EmailInput(attrs={'name': 'c_email', 'class': 'email form-control', 'id': 'email_id'}, ),
            'birthday': forms.DateInput(attrs={'type': 'date'}),
            'phone': forms.TextInput(attrs={'placeholder': 'example 09132985527'})

        }

    def clean_phone(self):
        phone = self.cleaned_data.get('phone')
        return check_phone(phone)

    def clean_name(self):
        name: str = self.cleaned_data.get('name')
        return name.capitalize()


class CarForm(forms.ModelForm):
    class Meta:
        model = Car
        fields = '__all__'

        widgets = {
            'customer': forms.Select(attrs={'class': 'select2'})
        }

customers/views.py
from django.shortcuts import render, HttpResponse
# Create your views here.
from django.views import View
from django.utils.translation import ugettext as _
from . import forms
from .models import Customer


class CreateCustomer(View):

    def post(self, request):
        form = forms.CustomerForm(self.request.POST, self.request.FILES)
        if form.is_valid():
            obj: Customer = form.save(commit=False)
            obj.status = False
            obj.save()
            return HttpResponse('Customer create')
        context = {
            'create_form': form
        }
        return render(request=self.request, template_name='customers/create_form.html', context=context)

    def get(self, request):
        form = forms.CustomerForm()
        context = {
            'create_form': form,
            'title': _('My site')
        }
        return render(request=self.request, template_name='customers/create_form.html', context=context)


class UpdateCustomer(View):

    def get(self, request, pk):
        c = Customer.objects.get(pk=pk)
        form = forms.CustomerForm(instance=c)
        context = {
            'create_form': form
        }
        return render(request=self.request, template_name='customers/create_form.html', context=context)


class CreateCar(View):

    def get(self, request):
        context = {
            'form': forms.CarForm()
        }

        return render(request=self.request, template_name='customers/car_form.html', context=context)

templates/customers/car_form.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'css/table.css' %}">
</head>
<body>
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>

    <input type="submit" value="create">
</form>
</body>
</html>

templates/customers/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="" method="post">
    {% csrf_token %}
    <label for="name">Name: </label>
    <input type="text" name="name" id="name" maxlength="150"> <br>
    <label for="email">Email</label>
    <input type="email" name="email" id="email"><br>
    <label for="date">Date:</label>
    <input type="date" id="date" name="date"><br>
    <label for="phone"></label>
    <input type="text" name="phone" id="phone" maxlength="13"><br>
    <label for="address">Address: </label>
    <textarea name="address" id="address"></textarea><br>
    <input type="submit" value="create">
</form>
</body>
</html>

templates/customers/create_form.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="{% static 'css/table.css' %}">
</head>
<body>
<div>
    {% get_current_language as LANGUAGE_CODE %}
    {% get_available_languages as LANGUAGES %}
    {% get_language_info_list for LANGUAGES as languages %}
    <ul>
        {% for lang in languages %}
            <li>
                <a href="/{{ lang.code }}/" {% if lang.code == LANGUAGE_CODE %} class="selected"{% endif %}>
                    {{ lang.name_local }}
                </a>
            </li>
        {% endfor %}
    </ul>

</div>
<form action="{% url 'customers:create' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <h1>{% trans 'This is a Header' %}</h1>
    <table>
        {{ create_form.as_table }}
    </table>

    <input type="submit" value="{% trans 'create' %}">
</form>
</body>
</html>

templates/customers/update_form.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
      integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="{% url 'project_index' %}">RP Portfolio</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'project_index' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blog_index' %}">Blog</a>
                </li>
            </ul>
        </div>
    </div>

</nav>

<div class="container">
    {% block page_content %}{% endblock %}
</div>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>